name: CloudMapper Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build CloudMapper Docker container
      run: |
        docker build -t nikolarendak/cloudmapper-1 .
        docker volume create cloudmapper-data-nikola

    - name: Scan AWS environment with CloudMapper
      run: |
        ls -la &&
        echo "test" >> README.md &&
        git add README.md && git commit -m "Test" && git push origin main &&
        ls &&
        cp -r /opt/cloudmapper/account-data/ /cloudmapper/account-data/ &&
        apt-get install -y git &&
        cd /cloudmapper/account-data/ &&
        git config --global user.email "nikola.rendak@gmail.com" &&
        git config --global user.name "nikolarendak" &&
        git init &&
        git add . &&
        git commit -m "Update account-data-nikola directory" &&
        git remote add origin https://github.com/nikolarendak/cloudmapper-1.git &&
        git push -u origin main
        sleep 45"
