name: CloudMapper Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build CloudMapper Docker container
      run: |
        docker build -t my-cloudmapper-docker .
        docker tag cloudmapper-docker:latest/home/bronson/cloudmapper-docker:latest
        docker push /home/bronson/cloudmapper/-docker:latest

    - name: Scan AWS environment with CloudMapper
      run: |
        docker run \
          -v $(pwd)/cloudmapper:/cloudmapper \
          -e -e AWS_PROFILE=rendakov \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          /home/bronson/cloudmapper/ \
          python3 cloudmapper.py collect --account Nikola_test_4 --no-upload
