name: CloudMapper Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build CloudMapper Docker container
      run: |
        docker build -t nikolarendak .
        docker volume create cloudmapper-data

    - name: Scan AWS environment with CloudMapper
      run: |
        docker run \
        -v cloudmapper-data-nikola:/opt/cloudmapper \
        -e TZ=Europe/Skopje \
        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        -e AWS_DEFAULT_REGION=eu-west-1 \
        -e TOKEN_GIT=${{ secrets.TOKEN_GIT }} \
        nikolarendak \
        bash -c "python cloudmapper.py configure add-account --config-file config.json --name Nikola_test_4 --id 796966033397 &&
        python cloudmapper.py collect --account Nikola_test_4 &&
        python cloudmapper.py report --account Nikola_test_4 &&
        python cloudmapper.py prepare --account Nikola_test_4 &&
        pwd &&
        ls &&
        cd opt/cloudmapper/web &&
        git config --global user.name "nikolarendak" &&
        git config --global user.email "nikolarendak@gmail.com" &&
        git add . && git commit -m "Update account-data-nikola directory" &&
        git push origin main"
